### ISSUE TITLE
Do not use std::path::Path in trait

### ISSUE THREAD

**Issue by rklaehn** [rkusa/sqlite-vfs#2]
Hi,

just found this. Nice project. I am trying to get sqlite to work with persistence in the browser via wasm. Was trying this out, but it does not compile to wasm due to using std::path::Path in the trait.

Can we use something else, like &str, that is available on all targets? I tried using &str here https://github.com/rklaehn/sqlite-vfs/tree/wasm , and at least the fs example still works.

Cheers,

Rüdiger

**Comment by rkusa** [comment]
Hi, thanks for the report. Good point, I didn't notice that `std::path::Path` isn't working for wasm - and I am assuming it is not working for `wasm32-unknown-unknown` specifically, because it builds fine for `wasm32-wasi`.

> I am trying to get sqlite to work with persistence in the browser via wasm.

You might be interested in https://github.com/rkusa/wasm-sqlite, which is build on top of `sqlite-vfs` and simplifies the storage down to fetching and saving pages. I'll get that out of experimental stage eventually (sometime after #1 landed).

> Can we use something else, like &str, that is available on all targets? I

I'll have to do some research whether using `str` is fine, or if it needs to be something like [`OsStr`](https://doc.rust-lang.org/std/ffi/struct.OsStr.html). I'll do that after #1 landed and also add `wasm32-unknown-unknown` builds to the CI with that.

**Comment by rklaehn** [comment]
I made a clone where I did several changes to make this work for my current use case: https://github.com/rklaehn/sqlite-vfs . I ended up using CStr, since that is basically what sqlite gives you.

I detached it since it might go in a different direction than yours. For example I expose all vfs methods so you can e.g. have a `wasm32-unknown-unknown`  compatible way to generate random numbers and current time. The number of things that don't work in the browser is quite large.

I think the best thing would be for some way to hook up custom VFSes to land in rusqlite. See https://github.com/rusqlite/rusqlite/issues/1145

**Comment by rklaehn** [comment]
By the way: the reason I am exploring this is because I love sqlite, use it in several of my projects (e.g. https://github.com/ipfs-rust/ipfs-embed ), and have been extremely annoyed by the existing persistence options in the browser.

I am working on a way to have persistent sqlite in the browser, using either the chrome files API or the generic cache api as a fallback.

**Comment by rkusa** [comment]
> I made a clone where I did several changes to make this work for my current use case: https://github.com/rklaehn/sqlite-vfs . I ended up using `CStr`, since that is basically what sqlite gives you.

My goal is to provide a very Rust-like interface and hide as much of the FFI as possible, so I'll probably try to avoid using `CStr` (the previously mentioned `OsStr` might not be a great candidate either with that rationale). Anyway, I'll give it more thought once #1 landed, which might come with some significant changes on the API anyway (to implement everything to make all tests green).

> have a `wasm32-unknown-unknown` compatible way to generate random numbers and current time. The number of things that don't work in the browser is quite large.

IMO, you might have an easier time compiling to `wasm-wasi` and provide the necessary wasi functions for things like random numbers and current time, e.g.: https://github.com/rkusa/wasm-sqlite/blob/main/src/lib.ts#L25-L30. But that is highly subjective, and just what I prefer to do.

Regarding #3, in case you are planing to suggest a PR, while I am definitely open to PRs, I think it would be a good idea to hold off on one until I am done with #1.

**Comment by rklaehn** [comment]
> My goal is to provide a very Rust-like interface and hide as much of the FFI as possible, so I'll probably try to avoid using CStr (the previously mentioned OsStr might not be a great candidate either with that rationale). Anyway, I'll give it more thought once #1 landed, which might come with some significant changes on the API anyway (to implement everything to make all tests green).

Yes, I saw that there were a lot of changes on that branch. I think for playing around I will for now just keep the interface low level. E.g. just use sqlite_sys codes directly in the errors instead of trying to go via std::io::Error.

> IMO, you might have an easier time compiling to wasm-wasi and provide the necessary wasi functions for things like random numbers and current time, e.g.: https://github.com/rkusa/wasm-sqlite/blob/main/src/lib.ts#L25-L30. But that is highly subjective, and just what I prefer to do.

I am not really an expert in wasm compilation. I am hacking on something that is meant to run well on both native and the web. The people that I collaborate with chose `wasm32-unknown-unknown`, so that's what I am doing.

In any case, just plugging in wasm compatible ways to do random numbers and time seems pretty straightforward.

> Regarding https://github.com/rkusa/sqlite-vfs/pull/3, in case you are planing to suggest a PR, while I am definitely open to PRs, I think it would be a good idea to hold off on one until I am done with https://github.com/rkusa/sqlite-vfs/pull/1.

Ideally I would love some of this work to make it to rusqlite. Let me play around and get something working. Thanks for the feedback so far.

**Comment by paulyoung** [comment]
For what it’s worth, I would also like to use this but must target `wasm32-unknown-unknown`
